<?php

namespace Database\Seeders;

use App\Models\Prestasi;
use Illuminate\Database\Seeder;

class PrestasiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Prestasi::truncate();

        $prestasiData = [
            [
                'nim' => 1317018,
                'nama_mahasiswa' => 'DANU RIZKY MAULANA',
                'ipk' => 0.0,
                'nama_kegiatan' => 'HMTI CUP II, Fakultas Teknik Universitas Muhammadiyah Banjarmasin',
                'waktu_penyelenggaraan' => '2019-01-01',
                'tingkat_kegiatan' => 'Provinsi',
                'prestasi_yang_dicapai' => 'Juara 2 Kategori Video Editing',
                'keterangan' => 'Akademik',
                'bukti_prestasi' => null,
                'pembimbing' => null,
            ],
            [
                'nim' => 1801301088,
                'nama_mahasiswa' => 'MUHAMMAD RAWILDHAN',
                'ipk' => 0.0,
                'nama_kegiatan' => 'HMTI CUP II, Fakultas Teknik Universitas Muhammadiyah Banjarmasin',
                'waktu_penyelenggaraan' => '2019-01-01',
                'tingkat_kegiatan' => 'Provinsi',
                'prestasi_yang_dicapai' => 'Juara 1 Kategori Mengetik Cepat',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => null,
                'pembimbing' => null,
            ],
            [
                'nim' => 1317018,
                'nama_mahasiswa' => 'DANU RIZKY MAULANA',
                'ipk' => 0.0,
                'nama_kegiatan' => 'Lomba Video Pendek Dalam Rangkaian Kegiatan Pekan Ilmiah, Uniska Banjarmasin',
                'waktu_penyelenggaraan' => '2019-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Juara 3',
                'keterangan' => 'Akademik',
                'bukti_prestasi' => null,
                'pembimbing' => null,
            ],
            [
                'nim' => 1801301088,
                'nama_mahasiswa' => 'MUHAMMAD RAWILDHAN',
                'ipk' => 0.0,
                'nama_kegiatan' => 'Unlam',
                'waktu_penyelenggaraan' => '2019-01-01',
                'tingkat_kegiatan' => 'Provinsi',
                'prestasi_yang_dicapai' => 'Juara 1 Mengetik Cepat',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => null,
                'pembimbing' => null,
            ],
            [
                'nim' => 1801301031,
                'nama_mahasiswa' => 'MARYANA',
                'ipk' => 0.0,
                'nama_kegiatan' => 'Lomba Nanang Galuh Dinas Pariwisata Kabupaten Tanah Laut',
                'waktu_penyelenggaraan' => '2019-01-01',
                'tingkat_kegiatan' => 'Kabupaten/Kota',
                'prestasi_yang_dicapai' => 'Juara 2',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => null,
                'pembimbing' => null,
            ],
            [
                'nim' => 1801301031,
                'nama_mahasiswa' => 'MARYANA',
                'ipk' => 0.0,
                'nama_kegiatan' => 'Duta Road Safety Polres Tanah Laut',
                'waktu_penyelenggaraan' => '2019-01-01',
                'tingkat_kegiatan' => 'Kabupaten/Kota',
                'prestasi_yang_dicapai' => 'Juara 2',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => null,
                'pembimbing' => null,
            ],
            [
                'nim' => 1901301099,
                'nama_mahasiswa' => "RAHMAH SA'ADAH",
                'ipk' => 3.49,
                'nama_kegiatan' => 'Walisongo Science Competition Tahun 2020, Cabang Lomba Karya Tulis Ilmiah, Fakultas Sains dan Teknologi, Universitas Islam Negeri Walisongo Semarang',
                'waktu_penyelenggaraan' => '2020-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Lolos Seleksi Administrasi',
                'keterangan' => 'Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => 'Wiwik Kusrini, S.Kom., M.Cs',
            ],
            [
                'nim' => 1901301123,
                'nama_mahasiswa' => 'TITIN SADIYAH',
                'ipk' => 2.66,
                'nama_kegiatan' => 'Walisongo Science Competition Tahun 2020, Cabang Lomba Karya Tulis Ilmiah, Fakultas Sains dan Teknologi, Universitas Islam Negeri Walisongo Semarang',
                'waktu_penyelenggaraan' => '2020-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Lolos Seleksi Administrasi',
                'keterangan' => 'Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => 'Wiwik Kusrini, S.Kom., M.Cs',
            ],
            [
                'nim' => 2001301057,
                'nama_mahasiswa' => 'SITI NURHALIZA',
                'ipk' => 2.72,
                'nama_kegiatan' => 'Lomba Cover Sholawat dalam Dies Natalis STIKES INTAN MARTAPURA 2021',
                'waktu_penyelenggaraan' => '2021-01-01',
                'tingkat_kegiatan' => 'Provinsi',
                'prestasi_yang_dicapai' => 'Juara 3',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => null,
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301092,
                'nama_mahasiswa' => 'M. REZA FAHLEVI',
                'ipk' => 3.9,
                'nama_kegiatan' => 'Kejuaraan Shorinji Kempo HUT Tanah Laut Ke-56 Se Kalimantan Selatan',
                'waktu_penyelenggaraan' => '2021-01-01',
                'tingkat_kegiatan' => 'Provinsi',
                'prestasi_yang_dicapai' => 'Juara 2 Embu Beregu Putera',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => null,
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301092,
                'nama_mahasiswa' => 'M. REZA FAHLEVI',
                'ipk' => 3.9,
                'nama_kegiatan' => 'Kejuaraan Shorinji Kempo HUT Tanah Laut Ke-56 Se Kalimantan Selatan',
                'waktu_penyelenggaraan' => '2021-01-01',
                'tingkat_kegiatan' => 'Provinsi',
                'prestasi_yang_dicapai' => 'Juara 2 Embu Berpasangan Putera',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => null,
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301096,
                'nama_mahasiswa' => 'MUHAMMAD ZAKI',
                'ipk' => 3.22,
                'nama_kegiatan' => 'Kejuaraan Shorinji Kempo HUT Tanah Laut Ke-56 Se Kalimantan Selatan',
                'waktu_penyelenggaraan' => '2021-01-01',
                'tingkat_kegiatan' => 'Provinsi',
                'prestasi_yang_dicapai' => 'Juara 2 Embu Beregu Putera',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => null,
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301076,
                'nama_mahasiswa' => 'Reihan Fariza',
                'ipk' => 3.44,
                'nama_kegiatan' => 'Kejuaran Provinsi Bridge Se-Kalimantan Selatan',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Provinsi',
                'prestasi_yang_dicapai' => 'Juara 1 Beregu U-21',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301076,
                'nama_mahasiswa' => 'Reihan Fariza',
                'ipk' => 3.44,
                'nama_kegiatan' => 'Kejuaran Provinsi Bridge Se-Kalimantan Selatan',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Provinsi',
                'prestasi_yang_dicapai' => 'Juara 3 Pasangan U-21',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2001301009,
                'nama_mahasiswa' => 'Annisa',
                'ipk' => 2.56,
                'nama_kegiatan' => 'Kejuaran Provinsi Bridge Se-Kalimantan Selatan',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Provinsi',
                'prestasi_yang_dicapai' => 'Juara 1 Pasangan U-21',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301091,
                'nama_mahasiswa' => 'Luthfi Adzhari',
                'ipk' => 3.29,
                'nama_kegiatan' => 'IMaBs Speech Competition, Universitas Muhammadiyah Yogyakarta',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => '10 besar',
                'keterangan' => 'Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2101402023,
                'nama_mahasiswa' => 'Nur Faisal Azma',
                'ipk' => 3.76,
                'nama_kegiatan' => 'IMaBs Speech Competition, Universitas Muhammadiyah Yogyakarta',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Juara Favorit',
                'keterangan' => 'Akademik',
                'bukti_prestasi' => null,
                'pembimbing' => null,
            ],
            [
                'nim' => 1901301007,
                'nama_mahasiswa' => 'Ahmad Nasrullah Yusuf',
                'ipk' => 2.59,
                'nama_kegiatan' => 'Kumite Perorangan +84 kg U-21 Putra, Kejur-Prov Karate Kalimantan Selatan 2022 ',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Provinsi',
                'prestasi_yang_dicapai' => 'Juara 3',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => null,
                'pembimbing' => null,
            ],
            [
                'nim' => 2101402023,
                'nama_mahasiswa' => 'Nur Faisal Azma',
                'ipk' => 3.76,
                'nama_kegiatan' => 'Politala English Competition 2022',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Internal (Kampus)',
                'prestasi_yang_dicapai' => 'Speech Champion',
                'keterangan' => 'Akademik',
                'bukti_prestasi' => null,
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301099,
                'nama_mahasiswa' => 'Nova Dwi Kesumawati',
                'ipk' => 3.45,
                'nama_kegiatan' => 'Politala English Competition 2022',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Internal (Kampus)',
                'prestasi_yang_dicapai' => 'Story Telling Champion',
                'keterangan' => 'Akademik',
                'bukti_prestasi' => null,
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301034,
                'nama_mahasiswa' => 'Miranda Arditha',
                'ipk' => 3.45,
                'nama_kegiatan' => 'Putri Otonomi Indonesia 2022',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Finalis',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2001301091,
                'nama_mahasiswa' => 'Diagne Alya Fidian',
                'ipk' => 3.59,
                'nama_kegiatan' => 'Beasiswa IISMAVO ke Jerman',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Mendapatkan Beasiswa IISMAVO ke Jerman',
                'keterangan' => 'Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301096,
                'nama_mahasiswa' => 'MUHAMMAD ZAKI',
                'ipk' => 3.22,
                'nama_kegiatan' => 'Kempo Randori Kelas 55Kg Putra, Porseni 2022',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Medali Emas (Juara 1)',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 1901301007,
                'nama_mahasiswa' => 'Ahmad Nasrullah Yusuf',
                'ipk' => 2.59,
                'nama_kegiatan' => 'Karate Kumite Over 84Kg Putra, Porseni 2022',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Medali Perak (Juara 2)',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 1901301023,
                'nama_mahasiswa' => 'ARYO RIANDITIA PRAHESTU',
                'ipk' => 2.67,
                'nama_kegiatan' => 'Kempo Randori Kelas 60Kg Putra, Porseni 2022',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Medali Perunggu (Juara 3)',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301079,
                'nama_mahasiswa' => 'ANNISA',
                'ipk' => 3.51,
                'nama_kegiatan' => 'Bridge Pasangan Putri, Porseni 2022',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Medali Perak (Juara 2)',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301076,
                'nama_mahasiswa' => 'Reihan Fariza',
                'ipk' => 3.44,
                'nama_kegiatan' => 'Bridge Beregu Campuran, Porseni 2022',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Medali Perunggu (Juara 3)',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301014,
                'nama_mahasiswa' => 'Noor Ridwansyah',
                'ipk' => 2.81,
                'nama_kegiatan' => 'Bridge Beregu Campuran, Porseni 2022',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Medali Perunggu (Juara 3)',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301079,
                'nama_mahasiswa' => 'ANNISA',
                'ipk' => 3.51,
                'nama_kegiatan' => 'Bridge Beregu Campuran, Porseni 2022',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Medali Perunggu (Juara 3)',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301076,
                'nama_mahasiswa' => 'Reihan Fariza',
                'ipk' => 3.44,
                'nama_kegiatan' => 'Bridge Pasangan Campuran, Porseni 2022',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Medali Emas (Juara 1)',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301014,
                'nama_mahasiswa' => 'Noor Ridwansyah',
                'ipk' => 2.81,
                'nama_kegiatan' => 'Bridge Pasangan Putra, Porseni 2022',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Medali Perunggu (Juara 3)',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301076,
                'nama_mahasiswa' => 'Reihan Fariza',
                'ipk' => 3.44,
                'nama_kegiatan' => 'Bridge Pasangan Putra, Porseni 2022',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Medali Perunggu (Juara 3)',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301099,
                'nama_mahasiswa' => 'Nova Dwi Kesumawati',
                'ipk' => 3.45,
                'nama_kegiatan' => 'Lomba Cipta dan Baca Puisi Dies Natalis Universitas Wahid Hasyim ke-22',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Juara 1',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => null,
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301034,
                'nama_mahasiswa' => 'Miranda Arditha',
                'ipk' => 3.45,
                'nama_kegiatan' => 'Nanang Galuh Kab. Tanah Laut 2022',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Kabupaten/Kota',
                'prestasi_yang_dicapai' => 'Juara Wakil IV ',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => null,
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301103,
                'nama_mahasiswa' => 'RAHMA WATI',
                'ipk' => 3.6,
                'nama_kegiatan' => 'Nanang Galuh Kab. Tanah Laut 2022',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Kabupaten/Kota',
                'prestasi_yang_dicapai' => 'Juara Wakil V',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => null,
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301099,
                'nama_mahasiswa' => 'Nova Dwi Kesumawati',
                'ipk' => 3.45,
                'nama_kegiatan' => 'Kompetisi "Baca Puisi" Peringatan HUT RI ke-77 Komunitas Literasi Karisma, Politeknik Negeri Sriwijaya',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Juara 3',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2101402025,
                'nama_mahasiswa' => 'OKTAVIA NADIA SARI',
                'ipk' => 3.32,
                'nama_kegiatan' => 'Antalogi Cerpen Tingkat Nasional, diselenggarakan oleh Penerbit Cahaya Smith Pratama',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Penulis Terbaik',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301099,
                'nama_mahasiswa' => 'Nova Dwi Kesumawati',
                'ipk' => 3.45,
                'nama_kegiatan' => 'Story Telling Contest at the Brotherhood English National Competition 2022',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Internal (Kampus)',
                'prestasi_yang_dicapai' => '1st place',
                'keterangan' => 'Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301079,
                'nama_mahasiswa' => 'ANNISA',
                'ipk' => 3.51,
                'nama_kegiatan' => 'PORPROV XI KalSel tahun 2022, Cabor Shorinji Bridge',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Provinsi',
                'prestasi_yang_dicapai' => 'Medali Emas',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301079,
                'nama_mahasiswa' => 'ANNISA',
                'ipk' => 3.51,
                'nama_kegiatan' => 'PORPROV XI KalSel tahun 2022, Cabor Shorinji Bridge',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Provinsi',
                'prestasi_yang_dicapai' => 'Medali Perunggu ',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301092,
                'nama_mahasiswa' => 'M. REZA FAHLEVI',
                'ipk' => 3.9,
                'nama_kegiatan' => 'PORPROV XI KalSel tahun 2022, Cabor Shorinji Kempo, Kelas Embu Berpasangan Putra - Kyu Kenshi',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Provinsi',
                'prestasi_yang_dicapai' => 'Medali Perunggu ',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301092,
                'nama_mahasiswa' => 'M. REZA FAHLEVI',
                'ipk' => 3.9,
                'nama_kegiatan' => 'PORPROV XI KalSel tahun 2022, Cabor Shorinji Kempo, Kelas Embu Beregu Putra - Kyu Kenshi',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Provinsi',
                'prestasi_yang_dicapai' => 'Medali Perak',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301096,
                'nama_mahasiswa' => 'MUHAMMAD ZAKI',
                'ipk' => 3.22,
                'nama_kegiatan' => 'PORPROV XI KalSel tahun 2022, Cabor Shorinji Kempo, Randori Kelas 55Kg Putera',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Provinsi',
                'prestasi_yang_dicapai' => 'Medali Perak',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301096,
                'nama_mahasiswa' => 'MUHAMMAD ZAKI',
                'ipk' => 3.22,
                'nama_kegiatan' => 'PORPROV XI KalSel tahun 2022, Cabor Shorinji Kempo, Kelas Embu Beregu Putra - Kyu Kenshi',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Provinsi',
                'prestasi_yang_dicapai' => 'Medali Perak',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2201301193,
                'nama_mahasiswa' => 'RAHMI ASHFIA',
                'ipk' => 3.56,
                'nama_kegiatan' => 'PORPROV XI KalSel tahun 2022, Cabor Tenis Lapangan',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Provinsi',
                'prestasi_yang_dicapai' => 'Medali Perunggu ',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2201301195,
                'nama_mahasiswa' => 'HADI PUTRA SETIAWAN',
                'ipk' => 3.75,
                'nama_kegiatan' => 'PORPROV XI KalSel tahun 2022, Cabor Bola Voli',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Provinsi',
                'prestasi_yang_dicapai' => 'Medali Perak',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2201301175,
                'nama_mahasiswa' => 'ANDIKA BAGUS PEBRIANTO',
                'ipk' => 2.53,
                'nama_kegiatan' => 'PORPROV XI KalSel tahun 2022, Cabor Shorinji Kempo',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Provinsi',
                'prestasi_yang_dicapai' => 'Medali Perunggu ',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2201301002,
                'nama_mahasiswa' => 'DAVID HADI NUGROHO',
                'ipk' => 3.05,
                'nama_kegiatan' => 'Speech Contest Competition HR Talent 2022, dengan tema "Gen Z Practicing the Creativity and Innovation Skills in the Spirit of Competition in Human Resource". Diselenggarakan oleh Himpunan Mahasiswa Manajemen Sumber Daya Manusia Aparatur Politeknik STIA L',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Finalist Top 10',
                'keterangan' => 'Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2201301067,
                'nama_mahasiswa' => 'HAYAT KHIZAR',
                'ipk' => 3.09,
                'nama_kegiatan' => 'Speech Contest Competition HR Talent 2022, dengan tema "Gen Z Practicing the Creativity and Innovation Skills in the Spirit of Competition in Human Resource". Diselenggarakan oleh Himpunan Mahasiswa Manajemen Sumber Daya Manusia Aparatur Politeknik STIA L',
                'waktu_penyelenggaraan' => '2022-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Finalist Top 10',
                'keterangan' => 'Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2001301152,
                'nama_mahasiswa' => 'NIMAS DIVA PRAMESWARI',
                'ipk' => 2.93,
                'nama_kegiatan' => 'Lomba Menulis Puisi Se-Asia #2',
                'waktu_penyelenggaraan' => '2023-01-01',
                'tingkat_kegiatan' => 'Internasional',
                'prestasi_yang_dicapai' => 'Peserta Terpilih',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2201301002,
                'nama_mahasiswa' => 'DAVID HADI NUGROHO',
                'ipk' => 3.05,
                'nama_kegiatan' => 'National Debate Competition at English Education Center OKUS (EDC-OKUS) Kampung Inggris Muaradua',
                'waktu_penyelenggaraan' => '2023-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Juara 1',
                'keterangan' => 'Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2201301067,
                'nama_mahasiswa' => 'HAYAT KHIZAR',
                'ipk' => 3.09,
                'nama_kegiatan' => 'National Debate Competition at English Education Center OKUS (EDC-OKUS) Kampung Inggris Muaradua',
                'waktu_penyelenggaraan' => '2023-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Juara 2',
                'keterangan' => 'Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2201301117,
                'nama_mahasiswa' => 'MUHAMMAD RAFLY KESUMA',
                'ipk' => 3.88,
                'nama_kegiatan' => 'National Story Telling Competition at English Education Center OKUS (EDC-OKUS) Kampung Inggris Muaradua',
                'waktu_penyelenggaraan' => '2023-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Juara 1',
                'keterangan' => 'Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2201301173,
                'nama_mahasiswa' => 'ADJI TAMA MUSTOFA PUTRA',
                'ipk' => 3.14,
                'nama_kegiatan' => 'Volly Putera, Rektor Cup III UIN Antasari Banjarmasin',
                'waktu_penyelenggaraan' => '2023-01-01',
                'tingkat_kegiatan' => 'Provinsi',
                'prestasi_yang_dicapai' => 'Juara 3',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2201301195,
                'nama_mahasiswa' => 'HADI PUTRA SETIAWAN',
                'ipk' => 3.75,
                'nama_kegiatan' => 'Volly Putera, Rektor Cup III UIN Antasari Banjarmasin',
                'waktu_penyelenggaraan' => '2023-01-01',
                'tingkat_kegiatan' => 'Provinsi',
                'prestasi_yang_dicapai' => 'Juara 3',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2001301072,
                'nama_mahasiswa' => 'SYAHRIL FAHMI',
                'ipk' => 3.58,
                'nama_kegiatan' => 'Festifal Olahraga Rekreasi Daerah (FORDA)',
                'waktu_penyelenggaraan' => '2023-01-01',
                'tingkat_kegiatan' => 'Provinsi',
                'prestasi_yang_dicapai' => 'Juara 1',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2101301038,
                'nama_mahasiswa' => 'GAZALI AKBAR',
                'ipk' => 3.59,
                'nama_kegiatan' => 'Festifal Olahraga Rekreasi Daerah (FORDA)',
                'waktu_penyelenggaraan' => '2023-01-01',
                'tingkat_kegiatan' => 'Provinsi',
                'prestasi_yang_dicapai' => 'Juara 1',
                'keterangan' => 'Non-Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2201301067,
                'nama_mahasiswa' => 'HAYAT KHIZAR',
                'ipk' => 3.09,
                'nama_kegiatan' => 'Lomba CSS NYTECOMP (National Youth Tech Competition) 2023',
                'waktu_penyelenggaraan' => '2023-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Juara 3',
                'keterangan' => 'Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => null,
            ],
            [
                'nim' => 2201301002,
                'nama_mahasiswa' => 'DAVID HADI NUGROHO',
                'ipk' => 3.05,
                'nama_kegiatan' => 'Kompetisi Mahasiswa Bidang Informatika Politeknik Nasional (KMIPN) V Kategori Pengembangan Aplikasi Bidang Permainan',
                'waktu_penyelenggaraan' => '2023-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Finalis dan Best Spirit',
                'keterangan' => 'Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => 'M. Najamudin Ridha',
            ],
            [
                'nim' => 2201301145,
                'nama_mahasiswa' => 'AINA JIRAH',
                'ipk' => 3.0,
                'nama_kegiatan' => 'Kompetisi Mahasiswa Bidang Informatika Politeknik Nasional (KMIPN) V Kategori Pengembangan Aplikasi Bidang Permainan',
                'waktu_penyelenggaraan' => '2023-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Finalis dan Best Spirit',
                'keterangan' => 'Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => 'M. Najamudin Ridha',
            ],
            [
                'nim' => 2201301126,
                'nama_mahasiswa' => 'LATIEF NAUPAL SIDIK',
                'ipk' => 3.31,
                'nama_kegiatan' => 'Kompetisi Mahasiswa Bidang Informatika Politeknik Nasional (KMIPN) V Kategori Pengembangan Aplikasi Bidang Permainan',
                'waktu_penyelenggaraan' => '2023-01-01',
                'tingkat_kegiatan' => 'Nasional',
                'prestasi_yang_dicapai' => 'Finalis dan Best Spirit',
                'keterangan' => 'Akademik',
                'bukti_prestasi' => 'Ada',
                'pembimbing' => 'M. Najamudin Ridha',
            ],
        ];

        foreach ($prestasiData as $data) {
            $data['prestasi_yang_dicapai'] = $this->getPrestasiCategory($data['prestasi_yang_dicapai']);
            Prestasi::create($data);
        }
    }

    public function getPrestasiCategory($prestasi) {
        $prestasi = strtolower($prestasi);
        if (str_contains($prestasi, 'juara 1') || str_contains($prestasi, 'medali emas') || str_contains($prestasi, '1st place') || str_contains($prestasi, 'juara i') || str_contains($prestasi, 'champion')) {
            return 'Juara 1';
        }
        if (str_contains($prestasi, 'juara 2') || str_contains($prestasi, 'medali perak') || str_contains($prestasi, 'juara ii')) {
            return 'Juara 2';
        }
        if (str_contains($prestasi, 'juara 3') || str_contains($prestasi, 'medali perunggu') || str_contains($prestasi, 'juara iii')) {
            return 'Juara 3';
        }
        return 'Lainnya';
    }
}